# lightning.pytorch==2.3.1
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  devices: 1
  num_nodes: 1
  precision: null
  logger: true
  callbacks:
  - class_path: mhclassmodel.MetricsAggCallback
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: /home/azureuser/SS4/ss4_sandbox/train/poctrain
      filename: checkpoint-{step:06d}-{val_loss:.2f}
      monitor: val_loss
      verbose: false
      save_last: true
      save_top_k: 3
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: 5000
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: 10
  min_epochs: 3
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 0.1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: /home/azureuser/SS4/ss4_sandbox/train/poctrain
model:
  inner_model:
    class_path: mhclassmodel.EsmTokenMhClassification
    init_args:
      model_name: facebook/esm2_t12_35M_UR50D
      use_pretrained_params: false
      dataset_path: data/AF_SWISS_Mu
      label_maps: null
      num_head_layers: 1
      hidden_dropout_prob: 0.1
  finetuned_from: data/step-245000.pt
  metrics_interval: 100
  ignore_index: -100
  optimizer: Adam
  optimizer_kwargs:
    lr: 1.0e-05
    weight_decay: 1.0e-07
  scheduler_kwargs:
    update_step: 5000.0
    warm_up_iter: 2.0
    warm_up_rate: 0.01
    exp_gamma: 0.95
data:
  dataset_path: data/AF_SWISS_Mu
  dataframe: null
  need_preprocess: false
  preprocess_to: null
  feature_col: seq
  label_cols:
  - Mu
  ignore_labels: []
  ignore_index: -100
  min_length: 3
  max_length: 800
  label_init_subsetsize: 5000
  label_maps: null
  data_seed: 42
  split_ratio:
  - 0.95
  - 0.04
  - 0.01
  batch_size: 5
  loader_thread: 5
  tokenizer_name: facebook/esm2_t12_35M_UR50D
  mask_rate: 0.1
ckpt_path: null
